extraction:
  python:
    python_setup:
      version: 3
      requirements_files:
        - requirements.txt
      setup_py: false

    after_prepare:
      - pip install tomlkit -t ./vendor
      - PYTHONPATH=./vendor python ./scripts/requirements.py
      - rm -r ./vendor
