extraction:
  python:
    python_setup:
      version: 3
      requirements_files:
        - requirements.txt
      setup.py: false

    after_prepare:
      - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - poetry install -v
      - poetry run pip freeze > requirements.txt
